language: python
python:
    - "3.4"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "wget https://launchpad.net/ubuntu/+archive/primary/+files/sqlite3_3.8.7.4-1_amd64.deb"
    - "sudo dpkg -i sqlite3_3.8.7.4-1_amd64.deb"
    - "pip3 install -r requirements.txt"
    - 'python3 -c "import sqlite3; print(sqlite3.sqlite_version)"'
script: "python3 manage.py test --webdriver=firefox"
