language: python
python:
    - "3.4"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "sudo apt-get update"
    - "sudo apt-get install libsqlite3-dev"
    - "pip3 install -r requirements.txt"
script: "python3 manage.py test --webdriver=firefox"
